language: shell
dist: focal

env:
  HADOLINT: "${HOME}/hadolint"

install:
  - curl -sL -o "$HADOLINT" "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" && chmod +x "$HADOLINT"

script:
  - shellcheck update.sh
  - shellcheck tools/adb-all
  - shellcheck tools/license_accepter
  - shellcheck tools-emulator/android-start-emulator
  - shellcheck tools-emulator/android-wait-for-emulator
  - shfmt -d -i 2 update.sh
  - shfmt -d -i 2 tools/adb-all
  - shfmt -d -i 2 tools/license_accepter
  - shfmt -d -i 2 tools-emulator/android-start-emulator
  - shfmt -d -i 2 tools-emulator/android-wait-for-emulator
  - $HADOLINT */Dockerfile
  - ./update.sh && git diff --exit-code
