language: shell
dist: bionic

env:
  SHFMT_URL: https://github.com/mvdan/sh/releases/download/v3.1.1/shfmt_v3.1.1_linux_amd64
  HADOLINT: "${HOME}/hadolint"

install:
  - curl -sSL $SHFMT_URL -o ~/shfmt && chmod +x ~/shfmt
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}

script:
  - ~/shfmt -d -i 2 update.sh
  - ~/shfmt -d -i 2 tools/adb-all
  - ~/shfmt -d -i 2 tools/license_accepter
  - ~/shfmt -d -i 2 tools-emulator/android-start-emulator
  - ~/shfmt -d -i 2 tools-emulator/android-wait-for-emulator
  - shellcheck update.sh
  - shellcheck tools/adb-all
  - shellcheck tools/license_accepter
  - shellcheck tools-emulator/android-start-emulator
  - shellcheck tools-emulator/android-wait-for-emulator
  - hadolint */Dockerfile
  - ./update.sh && git diff --exit-code
